# 流程描述
name: GitHub Actions Build and Deploy Horae
# 指定触发的条件：当master分支push时触发
on:
  push:
    branches:
      - master

# 任务
jobs:
  # 任务唯一ID/名字
  build-and-deploy:
    # 指定运行系统
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 步骤名字，按顺序执行
      # 1. 将代码拷贝到虚拟系统
      - name: Checkout
        # 用第三方库
        uses: actions/checkout@master
        with:
          # 持久化凭据
          persist-credentials: false

      # 2. 部署
      - name: Deploy
        # 用第三方库
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm rebuild node-sass && npm run docs:build && npm run build
